-- 006_seed_engagement.sql
--
-- Fixture-era seed was removed in feature/entity-id-freely-selectable.
-- Seed engagements are no longer created at migration time; operators
-- create engagements explicitly in the UI (PairSelector) against the
-- catalog populated by scripts/sync_entity_catalog.py.
--
-- Kept as an empty migration so migration history stays linear.
